[tool.black]
line_length = 79
skip-string-normalization = true
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  | \venv
)/
'''

[tool.isort]
profile = "black"
blocked_extensions = [
    "rst","html","js","svg","txt","css","scss","png","snap","tsx"
]
combine_as_imports = true
default_section = "THIRDPARTY"
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true
known_django = "django"
sections=["FUTURE","STDLIB","DJANGO","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
skip = [".git","__pycache__","LC_MESSAGES","venv"]
src_paths = ["."]
line_length = 79
multi_line_output = 3
no_lines_before="LOCALFOLDER"

[tool.pyright]
reportArgumentType = "none"
reportAttributeAccessIssue = false

[tool.mypy]
strict = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_equality = true
strict_concatenate = true
check_untyped_defs = true
disallow_subclassing_any = false
disallow_untyped_decorators = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_reexport = true
mypy_path = "src"
warn_return_any = false
explicit_package_bases = true
exclude = "(^venv/|venv/.*)"

[tool.flake8]
max-line-length = 79
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "*.pyc",
    "*.pyo"
]
ignore = [
    "E203",  # whitespace before ':'
    "W503",  # line break before binary operator
]